spring.application.name=portfolio

spring.datasource.url=jdbc:postgresql://ep-square-bird-aci0z8u4-pooler.sa-east-1.aws.neon.tech/portfolio?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_imoC5kEbKdf9

#colocar el dialecto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximun-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always

file.upload.dir=src/main/resources/static/img/projects

#Importante para que Spring sirva lo que se escribe en disco sin reiniciar
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/