spring.application.name=portfolio

spring.datasource.url=jdbc:postgresql://${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#colocar el dialecto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always

file.upload.dir=${FILE_UPLOAD_DIR}

#Importante para que Spring sirva lo que se escribe en disco sin reiniciar
spring.web.resources.static-locations=classpath:/static/,file:src/main/resources/static/


spring.threads.virtual.enabled=true